### ISSUE TITLE
General Todo For Live

### ISSUE THREAD

**Issue by bryanwillis** [MBIStaffing/website#22]
- Do we want links to other portals like healthcare dash?
- purchase all pictures
- optimize page loading 
- responsive testing
- Send to Creative Writer for Enhancements
- make sure all forms are set up and working
- inform search engines site is ready and tweak meta titles and descriptions - Bing, Yahoo, Google
- provide AMP site to google
- Get Toms approval to launch
- Inform social media sites of launch

**Comment by mayra1755** [comment]
Website Notes

Home Page:
1.	Need to come up with something to replace “you are who you hire”
2.	Blog Articles

Our Company Page:
1.	Change from “our company” to “about us”
2.	Our story needs to have pictures show up sooner or else it just shows a gray circle. Also, one of the pictures is missing.
3.	Core Values?
a.	Are we going to have anything in this section 
Talent Page:
1.	Can we make it so they can select more than one title
Employers Page:

Question- what type of positions are you trying to fill? Let them pick multiple positions 


I’m going to head out now but give me a call if you need me to explain any of these items

Thanks!

**Comment by mayra1755** [comment]
Bullet 1. Yes lets add the direct links to GoCo and Akken
Bullet 2. Lets wait for Tom to ok the pictures and then we will purchase them
Bullet 6. I like the Talent one we need to fix the Employer one a bit

**Comment by mayra1755** [comment]
About Us- doesn't show up when you are on the "employers page" still shows "our company"

Home Page: 
Change- "We are MBI" on the home page to just "MBI" and leave "simplifying the process of landing that next job or great hire" the same. 

Employer Page:
Could you make the form look more like the talent form? Sorry to change that up on you last minute. I just think it would look really nice if they both had the same layout. 

Contact Us Page:
Remember to put a link that takes you to both the Talent form and Employer form.

Blogs:
what page will the blogs go on?

**Comment by bryanwillis** [comment]
# General 
- purchase all pictures
- optimize page loading
- responsive testing
- send to creative writer (Austin)
- make sure all forms are set up and working
- notify search engines site is ready and tweak meta titles and descriptions - Bing, Yahoo, Google
- provide AMP site to google
- get approval to launch
- inform social media sites of launch
-  Add the direct links to GoCo and Akken

# [Home](http://mbistaffing.com/home) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/1)**
## Todo For Live

- [x] Banner loading
- [ ] Content review
- [x] Correct blog article and links 
- [x] Address Questions
- [x] Change We Are MBI to MBI

## Questions
- _Is the main banner loading still tweaking?_  I think I fixed it without needing a preloading logo/icon.
- _Do we want some sort of heading/intro in second section below the banner, i.e., _"You Are Who You Hire"_ ?_



# [About Us / Our Company](http://mbistaffing.com/about/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/2)**
## Todo For Live

- [ ] Review content and page flow
- [ ] Purchase remaining images if desired
- [x]  [Check out a few more about us pages](https://blog.hubspot.com/marketing/remarkable-about-us-page-examples#sm.000089rbjdqh1f58vjv1q9w6mvo4c)
- [ ] Fix learn more to call to action that scrolls to bottom of page like on homepage bottom section with links to other pages
- [x] Replace core values header with Why MBI
- [x] Address Questions 



## Questions
- _Are we for sure changing to About Us from Our Company?_ From the last meeting discussion, it sounded we decided to leave it after looking at formatting of [Verizon](http://www.verizon.com/about/) and a couple others. If we change, we should consider changing first section to something else to avoid repetitiveness. Possibly _**"At a Glance"**_ or even reverse them and change that to _**"Our Company"**_. People often look on "About Us" page for contact details which was one reason to consider something else although _**"Our Company"**_  probably presents the same issue. Probably overthinking this...
- _Are these images OK_?
- _Mayra can you possibly take a screenshot of what you see with images not showing up soon enough?_ If not I can check Monday at the office.


# [Contact](http://mbistaffing.com/contact/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/3)**

## Todo For Live

- [ ] Ensure business info correct and links are all working 
- [ ] Make sure info is accurate
- [ ] Address Questions

## Questions
- _Mayra about adding the links to the other pages this is what we decided, correct?_ I couldn't remember if it was that or using the [other contact page](http://mbistaffing.com/contact-old/). Sorry I know we talked about this aleady
- _Are we sure we don't we want the interactive live chat when available to provide more engaging user experience?_ 


# [Employers/Job Seekers](http://mbistaffing.com/employers/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/5)**

## Todo For Live

- [ ] Review Text
- [ ] Ensure forms are working exactly as desired
- [ ] Address Questions

## Todo For Future
- [ ] Add content (see Hired website for examples)

## Questions

- I think we decided not to have multiple titles because it would complicate the form if they select staffing partner and make it take too long (possibly losing the lead). Let me know if this is incorrect.  We might nneed to discuss the flow for that further. I changed it as to what we discussed in last meeting, but this should be reviewed.
- In your comment about making the form the same format, what part of the format are you referring to? 


# [Job Seekers](http://mbistaffing.com/job-seekers/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/6)**

- [ ] Review Text
- [ ] Ensure forms are working exactly as desired
- [ ] Address Question


## Questions

- _Do we need to change any form items here?_


# Blog Pages
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/18)**

## ToDo For Live

- [ ] Discuss articles with Katie and have Austin (creative writer / editor) post-edit
- [ ] Confirm pictures and purchase
- [ ] Share on Social Profiles on Launch day
- [ ] Add author pictures and descriptions
- [ ] Add author bios and add different author


### Blog Links

1. http://mbistaffing.com/better-worse-impact-trump-campaign-will-play-future-tech-jobs/
2. http://mbistaffing.com/3-steps-to-healthier-happier-work-life/
3. (insert here)

### Other ToDo's (Non Needed for launch)

- Add any other ideas - example of [similar layout](http://www.clickx.io/old-school-seo-dead)_
- Add Keywords, backlinks, and categories
- Add actual blog page once we have enough articles, i.e., http://mbistaffing.com/blog/
- Categories : Technical, Interview Tips, Salary, Career Advice, 

### Other Article Ideas

http://mbistaffing.com/land-next-job-today-10-tips-ace-interview/
http://mbistaffing.com/2017-tech-job-outlook-jobs-will-dominate-coming-year/
http://mbistaffing.com/top-it-degrees-job-outlook/
http://mbistaffing.com/contract-part-time-jobs/
http://mbistaffing.com/5-pro-tips-talent-acquisition-tech-2017/
http://mbistaffing.com/diversity-women-tech-2016-breakthrough-year/



# [Privacy](http://mbistaffing.com/privacy-policy/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/9)**


## ToDo For Live

- [ ] Ensure info is relevant and updated

## Questions
- _Do we need/want anything else or anything specific?_ I know that certain states (like California) require some sort of privacy policy on a website that collects user information. I think what we have is enough. I'm not sure if there's anything specific to job board sites.


# [Login](http://mbistaffing.com/login) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/17)**

## ToDo For Live
- [ ] Test login timeout


# [Terms of Use](http://mbistaffing.com/terms-of-use/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/19)**


## Questions

- Do we need terms of use / conditions or should these be merged with privacy (copyright, limit liability, governing law, etc)... [reading on this](https://www.freshbooks.com/blog/does-my-website-really-need-a-terms-and-conditions-page)






# [Thank You](http://mbistaffing.com/thank-you/) 
**[Github Issues Tracking](https://github.com/MBIStaffing/website/issues/20)**


## ToDo For Live

- [ ] Fix font
- [ ] Check links
- [ ] Remove Blog Link

## Questions 

- _Do we want different thank you text for each form?_ (job seeker, contact, employer)

**Comment by mayra1755** [comment]
1. Change to about us
2. I think the images are good but before we buy them lets check with Tom 
3. Screen shot has been sent
4. Mayra about adding the links to the other pages this is what we decided, correct? Yes that is correct
5. Are we sure we don't we want the interactive live chat when available to provide more engaging user experience? Yes I think email is good for now maybe for the second release. 
6. I think we decided not to have multiple titles because it would complicate the form if they select staffing partner and make it take too long (possibly losing the lead). Let me know if this is incorrect. We might nneed to discuss the flow for that further. I changed it as to what we discussed in last meeting, but this should be reviewed.- Yes lets review
7. In your comment about making the form the same format, what part of the format are you referring to?- I was thinking it would look nicer if the form looked similar to the talent one or maybe make it a bit bigger so more fields are visible.
8. Do we want different thank you text for each form? (job seeker, contact, employer)- I think we should have individual ones for each to add a personal touch.

**Comment by mayra1755** [comment]
Remember to change the "we are MBI" on the home page to just "MBI"

**Comment by mayra1755** [comment]
No need to put a header to replace "you are who you hire" I think it looks fine as is.

**Comment by bryanwillis** [comment]
Review WIth Tom

2. images / content 
6. I think we decided not to have multiple titles because it would complicate the form if they select staffing partner and make it take too long (possibly losing the lead). I changed it as to what we discussed in last meeting, but this should be reviewed.- Yes lets review
7. In your comment about making the form the same format, what part of the format are you referring to?- I was thinking it would look nicer if the form looked similar to the talent one or maybe make it a bit bigger so more fields are visible. _Tom originally mentioned he wanted each question showing individually so lets ask him. It might be hard showing more questions at once since they are dependent on the previous question.  _
